name: Push to PyPi

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  push:
    name: Push package to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies and build package from local
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Push dockerhub
        run: |
          pip install twine
          twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} --repository-url https://upload.pypi.org/legacy/ --verbose dist/*
